# Generated by Django 4.1.4 on 2023-05-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Мягколапки', 'Отдел мягких лапок'), ('Тыгыдыки', 'Отдел ночных тыгыдыков'), ('Закупщики', 'Отдел по закупкам корма'), ('Сони', 'Отдел по производству сладкого слипа'), ('Разработчики', 'Отдел разработки программ')], max_length=255, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('phone', models.TextField(null=True, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.position')),
            ],
        ),
        migrations.CreateModel(
            name='TradeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('members', models.ManyToManyField(to='core.worker')),
            ],
        ),
    ]
