# Generated by Django 4.1.4 on 2023-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='tradeunion',
            options={'verbose_name': 'Trade union', 'verbose_name_plural': 'Trade unions'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='tradeunion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название профсоюза'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.TextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Второе имя'),
        ),
    ]
